#!/usr/bin/env zsh

# not used
# - yabai
# - skhd

if [[ -z $STOW_FOLDERS ]]; then
  export STOW_FOLDERS="zsh,tmux,ideavimrc,nvim,btop,aerospace,gradle"
fi

if [[ -z $DOTFILES ]]; then
  export DOTFILES=$HOME/.dotfiles
fi

$DOTFILES/install
